- name: detail info data
  hosts: localhost
  tasks:
   - name: info
     vars:
      user:
       name: "Pradu"
       surname: "Pandit"
       address: "Pune"
       area: "Baner"
     command: echo {{user.name}} {{user.surname}}  {{user.address}} {{user.area}}
#     register: output
#   - debug: msg={{output}}
