- name: nested_looping
  hosts: localhost
  tasks:
   - name: loop
     shell: echo " {{item[0]}} {{item[1]}}"
     with_nested:
       - [ '2' ]
       - [ 'W','H' ]
#     register: output
#   - debug: msg={{output}}
- name: simple_looping
  hosts: localhost
  tasks:
   - name: loop
     shell: echo "{{item[0]}}"
     with_items:
       - [ '7','9' ]

