- name: random choose from list
  hosts: localhost
  tasks:
    - debug: msg="{{item}}"
      with_random_choice:
        - "something"
        - "nothing"
        - "everything"
    - shell: echo "testing"
      register: result
      #until: result.stdout.find("going") != -1
      retries: 4
      delay: 3
