- name: tag example
  hosts: localhost
  tasks: 
   - name: task1
     action: ping
   - name: tasks2
     command: echo "Just printing"
     tags: echo
     register: output
   - debug: msg={{output}}
     tags: print 

