---
- name: first playbool with web
  hosts: localhost
  vars:
    description: checking
  tasks:
   - name: 
     shell: echo "checking command" 
     register: output
   - debug: msg={{output}}
#   - name: ping
#     action: ping=localhost

- name: second playbook
  hosts: localhost
  tasks:
    - action: ping
      
...
